import { Card } from '../model/Card';
const cards: Card[] = [
  {
    ID: 0,
    back: 'Siyah',
    category: 'colors',
    exampleForeignLang: 'Kadın Siyah Elbise modelleri uygun fiyatlarla ve indirimlerle!',
    exampleUserLang: "Women's Black Dress models at affordable prices and discounts!",
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_0.mp3'),
    front: 'Black',
  },
  {
    ID: 1,
    back: 'Beyaz',
    category: 'colors',
    exampleForeignLang: 'Beyaz giyme söz olur',
    exampleUserLang: 'I promise to wear white (?)',
    // Test that nothing explodes when audio is missing
    // "foreignHeadwordAudio":
    //   require("../../assets/sounds/decks/dev-turkish/headword_foreign_1.mp3")
    front: 'White',
  },
  {
    ID: 2,
    back: 'Kırmızı',
    category: 'colors',
    exampleForeignLang: 'Kırmızı Mercimek Çorbası Tarifi (videolu) İçin Malzemeler',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_2.mp3'),
    front: 'Red',
  },
  {
    ID: 3,
    back: 'Mavi',
    category: 'colors',
    exampleUserLang: 'Blue is great!',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_3.mp3'),
    front: 'Blue',
  },
  {
    ID: 4,
    back: 'Turuncu',
    category: 'colors',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_4.mp3'),
    front: 'Orange',
  },
  {
    ID: 5,
    back: 'Yeşil',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_5.mp3'),
    front: 'Green',
  },
  {
    ID: 6,
    back: 'Mor',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_6.mp3'),
    front: 'Purple',
  },
  {
    ID: 7,
    back: 'Pembe',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_7.mp3'),
    front: 'Pink',
  },
  {
    ID: 8,
    back: 'Kahverengi',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_8.mp3'),
    front: 'Brown',
  },
  {
    ID: 9,
    back: 'Sarı',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_9.mp3'),
    front: 'Yellow',
  },
  {
    ID: 10,
    back: 'Gri',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_10.mp3'),
    front: 'Grey',
  },
  {
    ID: 11,
    back: 'Renk',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_11.mp3'),
    front: 'Color',
  },
  {
    ID: 12,
    back: 'Açık',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_12.mp3'),
    front: 'Light',
  },
  {
    ID: 13,
    back: 'Koyu',
    category: 'colors',
    exampleForeignLang: 'Neque porro quisquam est',
    exampleUserLang: 'qui dolorem ipsum quia dolor sit amet',
    foreignHeadwordAudio: require('../../assets/sounds/decks/dev-turkish/headword_foreign_13.mp3'),
    front: 'Dark',
  },
];

export default cards;
